In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchtext

ModuleNotFoundError: No module named 'torchtext'

In [ ]:
class SelfAtencion(nn.Module):
    def self_atencion(self, decoder_state: torch.Tensor, encoder_state: torch.Tensor):
        scores = torch.bmm(encoder_state, decoder_state.unsqueeze(1).transpose(1, 2))
        weights = nn.Softmax(dim=1)(scores)
        dim = encoder_state.shape
        output = torch.bmm(weights.flatten().view(dim[0],1,dim[1]), encoder_state)
        return output


In [105]:
# Datos para verificar
encoder_state = torch.ones(3, 4, 3)
encoder_state[0, :, :] = torch.tensor([[1,2,3], [1, 2, 3], [0, 2, 3], [1, 2, 3]])
encoder_state[1, :, :] = encoder_state[0, :, :] * 10
encoder_state[2, :, :] = encoder_state[0, :, :] * 100
print(encoder_state)
decoder_state = torch.ones(3, 3)
print(decoder_state)

tensor([[[  1.,   2.,   3.],
         [  1.,   2.,   3.],
         [  0.,   2.,   3.],
         [  1.,   2.,   3.]],

        [[ 10.,  20.,  30.],
         [ 10.,  20.,  30.],
         [  0.,  20.,  30.],
         [ 10.,  20.,  30.]],

        [[100., 200., 300.],
         [100., 200., 300.],
         [  0., 200., 300.],
         [100., 200., 300.]]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [107]:
sa = SelfAtencion()
output = sa.self_atencion(decoder_state, encoder_state)
print(output)

tensor([[[  0.8908,   2.0000,   3.0000]],

        [[  9.9998,  20.0000,  30.0000]],

        [[100.0000, 200.0000, 300.0000]]])
